server.port: 8087
spring:
  datasource:
    url: jdbc:mysql://101.132.194.164:3306/qq_bot?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 854473150
mybatis-plus:
  typeEnumsPackage: com.example.qbot.constants